### ISSUE TITLE
./make breaks

### ISSUE THREAD

**Issue by jjrbfi** [grotius-cnc/hal-core#11]
With the last commits got **./make** broken.

`/opt/hal-core/src/./make: line 3: ./configure: No such file or directory
g++: error: rtapi/uspace_rtapi_app.cc: No such file or directory
g++: fatal error: no input files
compilation terminated.
g++: error: rtapi/uspace_rtapi_parport.cc: No such file or directory
g++: fatal error: no input files
compilation terminated.
gcc: error: rtapi/uspace_rtapi_string.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
g++: error: rtapi/rtapi_pci.cc: No such file or directory
g++: fatal error: no input files
compilation terminated.
g++: error: objects/rtapi/uspace_rtapi_app.o: No such file or directory
g++: error: objects/rtapi/uspace_rtapi_parport.o: No such file or directory
g++: error: objects/rtapi/uspace_rtapi_string.o: No such file or directory
g++: error: objects/rtapi/rtapi_pci.o: No such file or directory
gcc: error: hal/utils/halcmd.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: hal/utils/halcmd_commands.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: hal/utils/halcmd_main.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: hal/utils/halcmd_completion.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: hal/hal_lib.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: rtapi/uspace_ulapi.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: objects/hal/hal_lib.o: No such file or directory
gcc: error: objects/rtapi/uspace_ulapi.o: No such file or directory
gcc: error: objects/hal/utils/halcmd.o: No such file or directory
gcc: error: objects/hal/utils/halcmd_commands.o: No such file or directory
gcc: error: objects/hal/utils/halcmd_main.o: No such file or directory
gcc: error: objects/hal/utils/halcmd_completion.o: No such file or directory
gcc: error: ../lib/libhalcore.so.0: No such file or directory
ln: failed to create symbolic link '../lib/libhalcore.so': No such file or directory
gcc: error: module_helper/module_helper.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: objects/module_helper/module_helper.o: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: hal/hal_lib.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
ld: cannot find objects/rthal/hal_lib.o: No such file or directory
objcopy: 'objects/hal_lib.tmp': No such file
/opt/hal-core/src/./make: line 75: objects/hal_lib.sym: No such file or directory
gcc: error: objects/rthal/hal_lib.o: No such file or directory
make: *** No rule to make target 'setuid'.  Stop.
gcc: error: test.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: test.o: No such file or directory
cp: cannot stat 'test.so': No such file or directory
./make: line 20: /opt/hal-core/src/hal/components/ethercat./make: No such file or directory
gcc: error: threads.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: threads.o: No such file or directory
cp: cannot stat 'threads.so': No such file or directory
`

I will try to get that working. But trying to be sure that all works before do commit.

**Comment by grotius-cnc** [comment]
Hi, 
It's just solved, by fixing the toplevel make file

**Comment by jjrbfi** [comment]
Great I just did some changes similar that you have to solve it. Thanks!
