### ISSUE TITLE
./make | dofs.so : No such file or directory

### ISSUE THREAD

**Issue by jjrbfi** [grotius-cnc/hal-core#13]
Looks like the dofs.so is not created or not in the place.

make: Entering directory '/opt/hal-core/src'
chown root ../bin/rtapi_app
chmod 4750 ../bin/rtapi_app
chown root ../bin/module_helper
chmod 4750 ../bin/module_helper
make: Leaving directory '/opt/hal-core/src'
/opt/hal-core/src/hal/components/dofs/cpp_interface/libdofs.so: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
cp: cannot stat 'dofs.so': No such file or directory

**Comment by grotius-cnc** [comment]
That's strange. I will have a look.

**Comment by grotius-cnc** [comment]
I did a workaround to solve this. Just curious, are you compiling on rpi4?

**Comment by jjrbfi** [comment]
I still have that issue compiling it.
Yes I'm using RPI4

**Comment by jjrbfi** [comment]
Got the same this the last commit we have:

make: Leaving directory '/opt/hal-core/src'
/opt/hal-core/src/hal/components/dofs/cpp_interface/libdofs.so: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
cp: cannot stat 'dofs.so': No such file or directory

**Comment by jjrbfi** [comment]
Maybe I missing some packages?

But I already installed all needed from src/README.md

**Comment by grotius-cnc** [comment]
try to do add ldconfig for the dir : $ sudo ldconfig /opt/hal-core/src/hal/components/dofs/cpp_interface
I think when compiling the dofs.so it can not find the c++ directory.

Maybe try to add this in the make file of /opt/hal-core/src/hal/components/dofs/make

**Comment by jjrbfi** [comment]
I got this error before your last edit:

```
ldconfig: /opt/hal-core/src/hal/components/dofs/cpp_interface/libdofs.so.1 is not a symbolic link

/opt/hal-core/src/hal/components/dofs/cpp_interface/libdofs.so: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
cp: cannot stat 'dofs.so': No such file or directory
```


I have the libdofs.so.1.0.0 located in rtlib right now.


_I also commented it and got al compiled (not the dofs) but will be nice to get that working also._

**Comment by grotius-cnc** [comment]
Hi, 
libdofs.so.1.0.0 is located in /rtlib when it is cloned. Maybe delete it from the /rtlib and let the compile procedure put it there.

The command to set a filepath for linux to search for libs is:
sudo ldconfig /opt/hal-core/src/hal/components/dofs/cpp_interface/

It is a idea to use symoblic links. What output is above command given?

**Comment by grotius-cnc** [comment]
Ok, i removed the .so files from the /rtlib. During the make process, everything will be put over there.

**Comment by jjrbfi** [comment]
I removed all the libdofs* from rtlib and them added sudo ldconfig /opt/hal-core/src/hal/components/dofs/cpp_interface/ and got this:


`make: Entering directory '/opt/hal-core/src'
chown root ../bin/rtapi_app
chmod 4750 ../bin/rtapi_app
chown root ../bin/module_helper
chmod 4750 ../bin/module_helper
make: Leaving directory '/opt/hal-core/src'
ldconfig: /opt/hal-core/src/hal/components/dofs/cpp_interface/libdofs.so.1 is not a symbolic link

/opt/hal-core/src/hal/components/dofs/cpp_interface/libdofs.so: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
cp: cannot stat 'dofs.so': No such file or directory
`

**Comment by jjrbfi** [comment]
I think I missing some packages for that maybe?

Quite rare have that issue that I had not before.

**Comment by grotius-cnc** [comment]
Yes strange. Haha

**Comment by grotius-cnc** [comment]
Ok. let's comment out the dofs lib for now in the make file. Then we focus on the ethercat bus.

**Comment by grotius-cnc** [comment]
I will comment it you now.

**Comment by jjrbfi** [comment]
I will recompile it changing **cc** to **gcc**.

https://github.com/grotius-cnc/hal-core/blob/main/src/hal/components/dofs/make#L6

Or should be cc?

**Comment by grotius-cnc** [comment]
just try it.

**Comment by jjrbfi** [comment]
Nope. the problem still. -_-´

**Comment by jjrbfi** [comment]
I will skip it for a bit to try to get EtherCAT working. Thanks!

**Comment by grotius-cnc** [comment]
Yes perfect !
